"""
Created by Yinghao Ho on 2026-2-23

SLSQP-based end-effector pose solver.
Wraps scipy SLSQP to optimise a 6D pose variable [pos(3), rvec(3)]
produced by ConstraintInstantiator, and returns a 4x4 homogeneous T for IKSolver.
"""

import sys
from typing import Dict, Callable

import numpy as np
from scipy.optimize import minimize, OptimizeResult

from utils import CoordinateTransformer


class PoseSolver:
    """SLSQP solver for end-effector pose. Consumes cost_fn and x0 from ConstraintInstantiator."""

    def __init__(self, max_iter: int = 200, tol: float = 1e-6, verbose: bool = True):
        self.max_iter = max_iter
        self.tol      = tol
        self.verbose  = verbose

    def solve(self,
              cost_fn: Callable[[np.ndarray], float],
              x0:      np.ndarray,
              meta:    Dict) -> Dict:
        """
        Run SLSQP on cost_fn starting from x0.

        Returns dict with keys:
            success, position, rotation_matrix, rvec, T, x_opt,
            final_cost, cost_breakdown, message, n_iter, x0
        """
        if self.verbose:
            print(f"[PoseSolver] initial cost: {cost_fn(x0):.6f}  pos: {np.round(x0[:3], 4)}")

        opt_result: OptimizeResult = minimize(
            fun=cost_fn,
            x0=x0,
            method='SLSQP',
            options={'maxiter': self.max_iter, 'ftol': self.tol, 'disp': False}
        )

        x_opt    = opt_result.x
        position = x_opt[:3]
        rvec     = x_opt[3:]
        R        = CoordinateTransformer.rodrigues(rvec)
        final_cost     = float(opt_result.fun)
        cost_breakdown = meta['cost_breakdown_fn'](x_opt)
        T = CoordinateTransformer.rotation_to_matrix4x4(position, R)

        result = {
            'success':         bool(opt_result.success),
            'position':        position.copy(),
            'rotation_matrix': R.copy(),
            'rvec':            rvec.copy(),
            'T':               T,
            'x_opt':           x_opt.copy(),
            'final_cost':      final_cost,
            'cost_breakdown':  cost_breakdown,
            'message':         opt_result.message,
            'n_iter':          int(opt_result.nit),
            'x0':              x0.copy(),
        }

        if self.verbose:
            status = "converged" if result['success'] else "not converged"
            print(f"[PoseSolver] {status} | iter={result['n_iter']} "
                  f"| cost={final_cost:.6f} | pos={np.round(position, 4)}")
            bd = cost_breakdown
            print(f"  C1 approach_pos={bd.get('approach_pos', 0.0):.6f}  "
                  f"C2 approach_rot={bd.get('approach_rot', 0.0):.6f}  "
                  f"C3 grasp_axis={bd.get('grasp_axis', 0.0):.6f}  "
                  f"C4 safety={bd.get('safety', 0.0):.6f}")
            if bd.get('safety_per_part'):
                for part, val in bd['safety_per_part'].items():
                    print(f"    safety[{part}]={val:.6f}")

        return result

    def solve_with_restart(self,
                           cost_fn:     Callable[[np.ndarray], float],
                           x0:          np.ndarray,
                           meta:        Dict,
                           n_restarts:  int   = 3,
                           noise_scale: float = 0.05) -> Dict:
        """
        solve() with random restarts around x0. Returns the lowest-cost result.
        n_restarts additional candidates are generated by adding Gaussian noise to x0.
        """
        if self.verbose:
            print(f"[PoseSolver] solve_with_restart: {n_restarts} restarts")

        candidates = [x0.copy()]
        rng = np.random.default_rng(seed=42)
        for _ in range(n_restarts):
            x0_noisy = x0.copy()
            x0_noisy[:3] += rng.normal(0, noise_scale,     size=3)
            x0_noisy[3:] += rng.normal(0, noise_scale * 2, size=3)
            candidates.append(x0_noisy)

        best_result  = None
        verbose_orig = self.verbose
        self.verbose = False
        for x0_candidate in candidates:
            result = self.solve(cost_fn, x0_candidate, meta)
            if best_result is None or result['final_cost'] < best_result['final_cost']:
                best_result = result
        self.verbose = verbose_orig

        if self.verbose:
            print(f"[PoseSolver] best cost={best_result['final_cost']:.6f}  "
                  f"pos={np.round(best_result['position'], 4)}  "
                  f"converged={best_result['success']}")

        return best_result


if __name__ == "__main__":
    sys.path.insert(0, '.')

    from modules.vlmDecider     import FALLBACK_DECISION
    from modules.constraintsInst import ConstraintInstantiator

    def make_cup_problem():
        keypoints_3d = {
            'handle': np.array([0.45,  0.07,  0.10]),
            'rim':    np.array([0.45,  0.00,  0.16]),
            'body':   np.array([0.45,  0.00,  0.08]),
        }
        inst = ConstraintInstantiator(verbose=False)
        return inst.instantiate(keypoints_3d, FALLBACK_DECISION)

    cost_fn, x0, meta = make_cup_problem()
    solver = PoseSolver(max_iter=200, tol=1e-6, verbose=True)
    result = solver.solve(cost_fn, x0, meta)

    required_keys = ['success', 'position', 'rotation_matrix', 'rvec',
                     'T', 'x_opt', 'final_cost', 'cost_breakdown',
                     'message', 'n_iter', 'x0']
    for key in required_keys:
        assert key in result, f"missing key: {key}"

    R = result['rotation_matrix']
    assert np.allclose(R.T @ R, np.eye(3), atol=1e-6)
    assert np.isclose(np.linalg.det(R), 1.0, atol=1e-6)

    T = result['T']
    assert np.allclose(T[:3, 3],  result['position'],        atol=1e-10)
    assert np.allclose(T[:3, :3], result['rotation_matrix'], atol=1e-10)
    assert np.allclose(T[3, :],   [0, 0, 0, 1],              atol=1e-10)

    bd = result['cost_breakdown']
    for field in ['approach_pos', 'approach_rot', 'grasp_axis', 'safety', 'flip']:
        assert field in bd, f"cost_breakdown missing: {field}"

    assert abs(bd['total'] - result['final_cost']) < 1e-6

    result_r = solver.solve_with_restart(cost_fn, x0, meta, n_restarts=3)
    assert result_r['final_cost'] <= result['final_cost'] + 1e-5

    from modules.vlmDecider import VLMDecision
    place_decision = VLMDecision(
        w_grasp_axis=0.0, w_safety=2.0, w_flip=1.5,
        confidence=0.0, reasoning="fallback", is_fallback=True
    )
    inst_t = ConstraintInstantiator(verbose=False)
    cost_fn_t, x0_t, meta_t = inst_t.instantiate(
        keypoints_3d={
            'surface': np.array([0.60, 0.10, 0.02]),
            'rim':     np.array([0.60, 0.10, 0.05]),
        },
        vlm_decision=place_decision,
    )
    result_t = solver.solve(cost_fn_t, x0_t, meta_t)
    assert result_t['cost_breakdown']['grasp_axis'] == 0.0

    print("all checks passed")